require 'active_record'
require 'securerandom'
require 'shotgun'
require 'sinatra'
require 'sinatra/activerecord'
require 'logger'
require 'yaml'
require 'haml'
require 'digest'

require 'server'
require 'url'